name: Deploy with VPN and SSH

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Installation de OpenConnect et Expect (pour SSH avec password)
    - name: Install OpenConnect and Expect
      run: sudo apt-get update && sudo apt-get install -y openconnect expect rsync

    # Connexion au VPN AnyConnect
    - name: Connect to VPN
      run: |
        echo "${{ secrets.VPN_PASSWORD }}" | sudo openconnect --background --user=${{ secrets.VPN_USERNAME }} --authgroup=Universite-de-Lorraine --passwd-on-stdin vpn.lothaire.net

    # Attendre que la connexion VPN soit établie
    - name: Wait for VPN connection
      run: sleep 10 && curl ifconfig.me

    - name: Ensure remote directory exists
      run: |
        expect -c "
        spawn ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \"mkdir -p /users/home/${{ secrets.SSH_USERNAME }}/CCD_Saperlipopette\"
        expect \"password:\"
        send \"${{ secrets.SSH_PASSWORD }}\r\"
        expect eof
        "

    # Copier tous les fichiers du dépôt + deploy.sh vers le serveur distant
    - name: Copy repository files to remote server
      run: |
        expect -c "
        spawn rsync -avz --delete -e \"ssh -o StrictHostKeyChecking=no\" ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/users/home/${{ secrets.SSH_USERNAME }}/CCD_Saperlipopette/
        expect \"password:\"
        send \"${{ secrets.SSH_PASSWORD }}\r\"
        expect eof
        "

    # Assurer que le script est exécutable et l'exécuter
    - name: Run deployment script
      run: |
        expect -c "
        spawn ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \"cd /users/home/${{ secrets.SSH_USERNAME }}/CCD_Saperlipopette && chmod +x deploy.sh && ./deploy.sh\"
        expect \"password:\"
        send \"${{ secrets.SSH_PASSWORD }}\r\"
        expect eof
        "

    # Déconnexion du VPN après le déploiement
    - name: Disconnect VPN
      if: always()
      run: sudo pkill openconnect
